name: Gettext updates
on:
  push:
    branches: main
jobs:
  gettext_template:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: elementary/actions/gettext-template@master
      env:
        GIT_USER_TOKEN: "${{ secrets.GIT_USER_TOKEN }}"
        GIT_USER_NAME: "cassidyjames"
        GIT_USER_EMAIL: "c@ssidyjam.es"
      with:
        translation_branch: 'main'
